L5 acceptance
yalokin/qna pull request #3
Opened 2017-06-14 17:28 UTC by yalokin

2017-06-14 17:49 UTC, vkurennov requested changes

2017-06-14 17:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
А где же тесты на destroy?

2017-06-14 17:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Тут нужно проверить, что ответ связывается с залогиненным юзером

2017-06-14 17:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>          expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
Тут нужно проверить, что вопрос связывается с залогиненным юзером

2017-06-14 17:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    let(:question) { create(:question) }
И опять нет тестов на destory. Прежде чем написать любой код, остановись и посмотри, есть ли у тебя на этот код тесты. И если нет, начни с них

2017-06-14 17:49 UTC, vkurennov commented on spec/acceptance/user_can_watch_questions.rb
> +      expect(page).to have_content question.title
Тест верный, но у тебя все вопросы одинаковые, поэтому он ложно-положительный, т.к. пройдет даже если на старнице один вопрос, просто дважды проверится один и тот же текст. Надо, используя sequence в фабриках, сделать все вопросы уникальными

2017-06-14 17:49 UTC, vkurennov commented on spec/acceptance/user_can_watch_question_and_answers_to_it_spec.rb
> +      expect(page).to have_content answer.body
Тут тоже, как и в случае с вопросами, надо их сделать уникальными через sequence в фабриках

2017-06-14 17:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
А где тесты на ассоциации и метод `author_of?`

2017-06-15 14:42 UTC, yalokin commented on spec/acceptance/user_can_watch_question_and_answers_to_it_spec.rb
> +      expect(page).to have_content answer.body
Здесь сделал еще одну последовательность body, но тесты заругались, что уже есть такая. Как правильнее сделать, использовать ее из вопросов или сделать в ответах еще одну под другим именем?  Пока сделал под другим именем

2017-06-15 19:16 UTC, iBublik requested changes

2017-06-15 19:16 UTC, iBublik commented on app/views/questions/show.html.slim
> +- if current_user && current_user.author_of?(@question)
Если у тебя версия Ruby 2.3 и выше, можно писать `if current_user&.author_of?(@question)` - это safe navigation operator, позволяет избежать проверок на nil.

2017-06-15 19:16 UTC, iBublik commented on db/migrate/20170613170043_add_questions_to_user.rb
> +    add_belongs_to :questions, :user, index: true
`index: true` можно не писать, т.к. он по умолчанию создается. А вот `foreign_key: true` писать стоит - без внешних ключей жить грустно :)

2017-06-15 19:16 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to_not have_content 'Delete answer'
В аксептанс спеках для отрицания лучше использовать капибаровские матчеры (вместо `to_not have_content` => `to have_no_content`). В них встроено ожидание - если на странице есть элемент, то капибара будет с некоторым интервалом проверять его отсутствие, пока не превысится максимальное время ожидания. Это полезно на страницах с js, когда элемент скрывается каким-нибудь скриптом. Сейчас у нас статичные страницы, но в целом лучше сразу начать пользоваться правильным инструментом.

2017-06-15 19:16 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +  given!(:question) { create :question }
Зачем злоупотреблять бэнг версией? Ее нужно использовать только когда объект нужно создать на начало теста, а у тебя тут в половине тестов объекты не используются. Когда тестов будет много, это станет проблемой - запись в БД дорогая операция

2017-06-15 19:16 UTC, iBublik commented on spec/acceptance/sign_out_spec.rb
> +    User.create!(email: 'user@test.ru', password: '12345678')
Для создания объектов у нас есть фабрики. Ты даже написал вышел хелпер для создания пользователя, только не использовал его

2017-06-15 19:16 UTC, iBublik commented on spec/acceptance/user_can_watch_question_and_answers_to_it_spec.rb
> +      expect(page).to have_content answer.body
Потому что ты создал последовательности в глобальном пространстве FactoryGirl. Если описывать последовательность внутри фабрики, то она будет видима только там:
```ruby
FactoryGirl.define do
  factory :answer do
    sequence(:body) { |n| "AnswerBody-#{n}" }
  end

  factory :question do
    sequence(:body) { |n| "QuestionBody-#{n}" }
  end
end
```

А общие последовательности лучше выделить в отдельный файл `sequences.rb`, там объявить их в глобальном пространстве FactoryGirl, тогда можно будет переиспользовать их в разных фабриках.

2017-06-15 19:34 UTC, iBublik commented on app/views/questions/show.html.slim
> +    - if current_user && current_user.author_of?(answer)
Лишний отступ, из-за этого тест не проходит

2017-06-15 19:37 UTC, iBublik commented on app/views/questions/show.html.slim
> +    - if current_user && current_user.author_of?(answer)
Потом упадет из-за другого, но ты попробуй сам разобраться. Если не получится - пиши :)

2017-06-16 15:16 UTC, yalokin commented on spec/acceptance/user_can_watch_question_and_answers_to_it_spec.rb
> +      expect(page).to have_content answer.body
Спасибо, очень хорошее замечание. Вам стоит об этом рассказать в комментариях к скринкасту, а то ведь некрасиво получается глобальная последовательность лежит в questions

2017-06-16 15:23 UTC, yalokin commented on app/views/questions/show.html.slim
> +- if current_user && current_user.author_of?(@question)
& не сразу заметил )

2017-06-16 16:02 UTC, yalokin commented on spec/acceptance/delete_answer_spec.rb
> +  given!(:question) { create :question }
Убрал везде, чтобы тесты проходили. Перечитал заново сообщение на форуме, но все же не совсем понял почему так или так

2017-06-16 17:04 UTC, yalokin commented on app/views/questions/show.html.slim
> +    - if current_user && current_user.author_of?(answer)
теперь падает два теста, хотя в интерфейсе выводится как надо. Честно сказать не пойму в чем же дело

2017-06-16 17:22 UTC, yalokin commented on app/views/questions/show.html.slim
> +    - if current_user && current_user.author_of?(answer)
Добился, что один, но кнопку капибара не видит, а я вижу

2017-06-16 17:32 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +  given!(:question) { create :question }
Суть бэнг метода - выполнить код из хелпера до начала теста.
В случае со списком вопросов, без бэнг метода была следующая последовательность:
1. В тесте ты заходил на страницу вопроса
2. Отрабатывал код приложения, контроллер вызывал метод для получения ответов на впорос из базы. Но там было пусто, т.к. твой хелпер для создания списка ответов еще не вызывался. Поэтому на странице было пусто
3. Далее тест проверял `answers.each ...` - вот в этот момент вызывался хелпер и ответы создавались. Но страница-то уже отрендерена на этот момент, так что толку от создания вопросов нет - страница пустая.
В случае с бэнг методом, уже на шаге 1 ответы созданы в базе. Поэтому и тест проходит.
Вывод простой - когда на начало теста нам нужны данные, используем бэнг-метод. Во всех остальных случаях используем обычный метод, чтоб код выполнялся только в момент обращения.

2017-06-16 17:35 UTC, iBublik commented on app/views/questions/show.html.slim
> +    - if current_user && current_user.author_of?(answer)
Проблема в том, что при создании невалидного ответа он не сохраняется в базу и у него нет id. А у тебя код `@question.answers.each ...` перебирает все ответы и рендерит для них ссылку на удаление, которая падает при отсутствии id. Решение простое - проверять сохранен ли ответ в базу (`persisted?`), и только тогда рендерить для него ссылку на удаление

2017-06-16 17:52 UTC, iBublik requested changes

2017-06-16 17:52 UTC, iBublik commented on spec/models/user_spec.rb
> +  describe 'author_of? method' do
Тесты инстанс методов описываются как `describe '#author_of?'`

2017-06-16 17:52 UTC, iBublik commented on app/views/questions/index.html.slim
> +          li = link_to question.title, question_path(question)
В слиме важно соблюдать правильный уровень отступов. Так что лучше выровняй эту строку, чтоб потом проблем не было

2017-06-16 17:52 UTC, iBublik commented on db/migrate/20170613213946_add_answers_to_user.rb
> +    add_belongs_to :answers, :user, index: true
Здесь замечание про внешний ключ тоже актуально. Все связи должны быть построены с использоваием внешних ключей

2017-06-16 17:52 UTC, iBublik commented on app/views/questions/show.html.slim
> +- unless @question.answers.count.to_i.zero?
Это не решение - при наличии ответов у вопроса и попытке создания невалидного ответа этот хак не поможет.
Я описал в чем проблема - https://github.com/yalokin/qna/pull/3/files/c197272be69bcb14cd43e8c69a353ebc99b47959#r122494380

2017-06-16 17:52 UTC, iBublik commented on spec/acceptance/delete_answer_spec.rb
> +  given(:answer) { create(:answer, user: user, question: question) }
Вот тут как раз зря убрал бэнг метод. Нам нужно иметь в базе ответ на начало всех тестов, чтобы проверить отсутствие/наличие ссылки.

2017-06-17 08:43 UTC, yalokin commented on app/views/questions/show.html.slim
> +    - if current_user && current_user.author_of?(answer)
Здесь тоже не совсем понятно как именно это работает и где у меня пробел в знаниях. Как так получается, что @question.answers.each ...  перебирает в том числе ответ, который не прошел валидацию и не записался в базу?

2017-06-17 09:17 UTC, yalokin commented on spec/acceptance/delete_answer_spec.rb
> +  given!(:question) { create :question }
Спасибо за такой развернутый ответ. Теперь значительно понятнее

2017-06-17 10:29 UTC, vkurennov approved these changes

2017-06-17 12:21 UTC, iBublik commented on app/views/questions/show.html.slim
> +    - if current_user && current_user.author_of?(answer)
@yalokin в памяти он уже ассоциирован с вопросом, т.к. ты создал его через `@question.answers.new`

2017-06-19 20:18 UTC, merged