L7 ajax
yalokin/qna pull request #5
Opened 2017-07-01 13:29 UTC by yalokin

2017-07-01 20:07 UTC, iBublik requested changes

2017-07-01 20:07 UTC, iBublik commented on app/assets/javascripts/answers.coffee
> +  answer_id = $(this).data('answerId')
В JS принято использовать camelCase (`answerId`)

2017-07-01 20:07 UTC, iBublik commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
Если пользователь не автор ответа, то отренедрится та же вьюха `destroy.js.erb` и ответ удалится со страницы (но не из базы).

2017-07-01 20:07 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer.best! if current_user.author_of?(@answer.question)
Тут проблема аналогична `destroy` - даже для не-автора будет рендериться тот же `best.js.erb`, и ответ визуально станет "лучшим".

2017-07-01 20:07 UTC, iBublik commented on app/models/answer.rb
> +  validates_uniqueness_of :best, conditions: -> { where(best: true) }, scope: :question_id
Всегда используй новый формат валидаций (`validates :best, uniqueness: { ... }`)

2017-07-01 20:07 UTC, iBublik commented on app/models/answer.rb
> +  validates_uniqueness_of :best, conditions: -> { where(best: true) }, scope: :question_id
Лично мое мнение - валидации должны быть только на те вещи, которые целиком контролирует пользователь. Например, какие-то параметры в форме. Логика установки лучшего ответа полностью описывается разработчиком, пользователь не влияет на снятие флага с предыдущего лучшего ответа, так что нет смысла добавлять на это валидацию. Если накосячисл разработчик, страдать будут обычные пользователи :)
Предположим, что как-то так вышло, что к одному ответу выбралось 2 лучших ответа. Тогда автор одного из таких ответов не сможет его отредактировать - валидация будет падать, при этом сделать с этим он ничего не сможет (дубликат возник из-за ошибки где-то в недрах нашей системы).
Тем не менее, в реальной системе допускать таких оплошностей (2 лучших ответа) нельзя. И вот тут на помощь уже приходит база данных - в этом случае рекомендуется навесить условный уникальный индекс на пару полей `question_id, best`. Условный, чтоб контролировать уникальность только если значение поля `best` равно `true`. Тогда у нас в базе точно никогда не будет 2 лучших ответа для одного вопроса - просто будет падать ошибка при попытке создания дубликата. В учебном приложении индекс не обязательно делать, но если хочешь - дерзай (там не так сложно, все есть в документации к миграциям).

2017-07-01 20:07 UTC, iBublik commented on app/models/answer.rb
> +    prev_best = question.answers.where(best: true)
В принципе не обязательно делать условие на `best: true`. Если мы просто проапдейтим все ответы текущего вопроса, то логически ничего не изменится.

2017-07-01 20:07 UTC, iBublik commented on app/models/answer.rb
> +    update(best: true)
Это действие и снятие флага `best` с предыдущего вопроса лучше делать в транзакции, причем тут использовать бэнг метод `update!`. Тогда если что-то упало, то откатятся оба действия разом - это называется атомарность (либо успешны все действия, либо ни одно)

2017-07-01 20:07 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +    - if answer.best
Для всех атрибутов Rails генерирует методы-предикаты. Вот тут можно использовать его для лучшей читабельности - `if answer.best?`

2017-07-01 20:07 UTC, iBublik commented on app/views/answers/best.js.erb
> +<% if @answer.errors.any? %>
С учетом моего замечания по поводу валидации, эта проверка будет избыточной

2017-07-01 20:07 UTC, iBublik commented on app/views/questions/_question.html.slim
> +  p = @question.title
Почему внезапно инстанс-переменная?

2017-07-01 20:07 UTC, iBublik commented on spec/acceptance/best_answer_spec.rb
> +    expect(page).to have_content 'Best answer'
Еще нужно проверить, что лучший ответ стал первым в списке. Для этого лучшим надо выбирать обязательно не первый ответ

2017-07-01 20:07 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATCH #UPDATE' do
`update` строчными пиши, это же просто название метода контроллера

2017-07-01 20:07 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).best).to eq true
`expect(assigns(:answer)).to be_best` - не забывй про фичу RSpec для методов-предикатов

2017-07-01 20:07 UTC, iBublik commented on spec/models/answer_spec.rb
> +  let(:another_answer) { question.answers.second }
Имхо, проще записать так:
```ruby
let(:question) { create :question }
let(:answer) { create :best_answer, question: question }
let(:another_answer) { create :answer, question: question }
```

2017-07-01 20:07 UTC, iBublik commented on spec/models/answer_spec.rb
> +      answer.best!
В тесте метода мы не должны пользоваться им самим для установки данных - а вдруг в нем ошибка? Так что лучше инкапсулируй логику создания лучшего ответа в фабрику (`best_answer`)

2017-07-01 20:07 UTC, iBublik commented on spec/models/answer_spec.rb
> +      answer.reload
Тест описан странно - в нем ничего не происходит, кроме перезагрузки ответа. Более корректно будет так - был обычный ответ, вызвали у него метод `best!`, а потом проверили что он стал лучшим `expect(another_answer.reload).to be_best`

2017-07-01 20:07 UTC, iBublik commented on spec/models/answer_spec.rb
> +      answer.reload
Ну и в отдельном тесте проверить, что предыдущий лучший сбросил флаг

2017-07-01 20:07 UTC, iBublik commented on spec/models/answer_spec.rb
> +    it 'can change best answer' do
Почему `can`? Разве возможна ситуация, когда метод не поменяет лучший ответ? Посмотри на досуге  http://www.betterspecs.org/ru/#should, там еще много других рекомендация по описанию спеков

2017-07-01 20:07 UTC, iBublik commented on spec/models/answer_spec.rb
> +    it 'can not set more than one best answer' do
Это уже не тест метода. Это тест валидации, а для этого у нас есть shoulda-matchers. Но т.к. я рекомендую валидацию выбросить, то тест тоже не нужен (если добавишь индекс, то можно наличие индекса протестить)

2017-07-01 20:07 UTC, iBublik commented on spec/models/answer_spec.rb
> +  describe 'ordered scope' do
Методы класса (а скоуп им является) описываются через точку (`describe .ordered`). Чтоб подчеркнуть, что это скоупы, можно вложить в другой describe:
```ruby
describe 'scopes' do
  describe '.ordered' do
    ...
  end
end

2017-07-03 14:27 UTC, yalokin commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
а ведь кнопки не будет

2017-07-03 15:39 UTC, yalokin commented on app/models/answer.rb
> +  validates_uniqueness_of :best, conditions: -> { where(best: true) }, scope: :question_id
Помучился немного, но вроде сделал )

2017-07-03 15:45 UTC, yalokin commented on app/models/answer.rb
> +    prev_best = question.answers.where(best: true)
а с точки зрения производительности? Ведь если ответов 1000, обновить их будет дольше, чем найти нужный и обновить только его?

2017-07-03 16:26 UTC, yalokin commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).best).to eq true
Я про нее не знал )

2017-07-03 16:46 UTC, iBublik commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
Кнопки не будет, но ведь запрос можно и ручками :) Мы для этого и делаем проверки в контроллере

2017-07-03 16:53 UTC, iBublik commented on app/models/answer.rb
> +    prev_best = question.answers.where(best: true)
Точного ответа я не знаю - СУБД скрывают в себе детали реализации, так что надо смотреть планы выполнения запроса. На 1000 строк вряд ли будет заметна разница, на 1_000_000 уже возможно. В общем, можешь оставить как есть, а свой вопрос задать на форуме - возможно кто-то сталкивался с этим и знает ответ из практики

2017-07-03 16:54 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).best).to eq true
Хм, мы обычно про нее рассказываем в занятии с acceptance тестированием на примере метода `author_of?`

2017-07-04 05:32 UTC, iBublik requested changes

2017-07-04 05:32 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'You can not edit this answer'
Этот флеш отобразится только при следующей полной перезагрузке страницы

2017-07-04 05:32 UTC, iBublik commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
Замечание актуально

2017-07-04 05:32 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer.best! if current_user.author_of?(@answer.question)
И это тоже.

2017-07-04 05:32 UTC, iBublik commented on app/models/answer.rb
> +      prev_best.first.update!(best: false) unless prev_best.empty?
Чтобы не делать `first` можно было написать `prev_best = question.answers.find_by(best: true)`. 
А вообще мне предыдущий вариант даже больше нравился - мы ничего не грузили в память, update делали на уровне запроса

2017-07-04 05:32 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +  - if answer.persisted?
А div-то даже для несохраненного ответа сгенерится :) И вообще эту проверку я бы вынес из партиала, уж больно специфичная она

2017-07-04 05:32 UTC, iBublik commented on app/views/questions/_question.html.slim
> +- if question.persisted?
Это я бы тоже вынес из партиала

2017-07-04 05:32 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +      it 'set best to true' do
Тут бы более высокоуровневое описание, ез деталей реализации. Например `it 'makes answer best'`

2017-07-04 05:32 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).best).to eq false
Используй матчеры для предикатов, я же выше писал - `expect(assigns(:answer)).to_not be_best`

2017-07-04 05:32 UTC, iBublik commented on spec/models/answer_spec.rb
> +
А куда пропал тест сброса флага у предыдущего лучшего ответа? Он тоже важен

2017-07-04 05:32 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      flash[:notice] = 'You can not delete this answer'
Тут с флешами та же проблема

2017-07-04 10:51 UTC, yalokin commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
это мне надо рендеринг шаблона определенного сделать или же это настраивать девайс, как в предыдущих уроках?

2017-07-04 11:09 UTC, yalokin commented on app/models/answer.rb
> +      prev_best.first.update!(best: false) unless prev_best.empty?
Надо пожалуй active record освежить по поводу загрузки в память

2017-07-04 11:49 UTC, yalokin commented on app/views/questions/_question.html.slim
> +- if question.persisted?
это вынес

2017-07-04 11:50 UTC, yalokin commented on app/views/answers/_answer.html.slim
> +  - if answer.persisted?
а вот здесь не вижу как можно красиво вынести, если вызывается в шаблоне как 
= render @question.answers.ordered
пока - if answer.persisted? поставил выше дива

2017-07-04 11:54 UTC, yalokin commented on spec/models/answer_spec.rb
> +
подумал, что субд теперь проверяет и нет смысла в нем

2017-07-04 12:29 UTC, yalokin commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
Вроде все остальное сделал, а здесь я в замешательстве

2017-07-04 19:58 UTC, iBublik commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
Самый простой вариант - просто сделать `redirect_to @answer.question, notice: 'You can not delete this answer'`.
Про devise вопроса не понял

2017-07-05 08:51 UTC, yalokin commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
Вроде как помню через девайс можно настроить так, чтобы при запросе к экшну, который требует авторизации автоматом перенаправлял например на страницу входа. 
И еще, тестировал я этот момент так, открывал две вкладки, на одной разлогинивался, а на другой пробовал удалить ответ, в ответе приходит это https://pastebin.com/PXvZuqEW
Что-то  я не уверен, что так нормально

2017-07-05 09:03 UTC, vkurennov requested changes

2017-07-05 09:03 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, notice: 'You can not delete this answer'
Редирект смысла делать нет, у тебя же ajax-запрос, редирект будет в фоне, браузер не перейдет на страницу

2017-07-05 09:03 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, notice: 'You can not set best answer'
Опять же редирект не имеет смысла для ajax-запросов

2017-07-05 09:03 UTC, vkurennov commented on app/models/answer.rb
> +      prev_best.update(best: false)
Транзакция откатывается только в случае исключения,  update не выбрасывает исключение, а возвращает false

2017-07-05 09:03 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +- if question.persisted?
А почему тогда здесь осталась эта проверка?

2017-07-05 10:12 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question, notice: 'You can not delete this answer'
Это мой дурной совет

2017-07-06 06:21 UTC, vkurennov approved these changes

2017-07-14 17:23 UTC, merged