Polymorphic
yalokin/qna pull request #6
Opened 2017-07-14 17:24 UTC by yalokin

2017-07-14 19:56 UTC, iBublik requested changes

2017-07-14 19:56 UTC, iBublik commented on app/models/answer.rb
> +      prev_best.update(best: false) unless prev_best.empty?
Зря убрал бэнг версию - теперь если что-то пошло не так, транзакция не откатится. А чтоб не проверять на пустоту, можно воспользоваться оператором & - `prev_best&.update!(best: false)`

2017-07-14 19:56 UTC, iBublik commented on app/models/answer.rb
> +  accepts_nested_attributes_for :attachments
Добавь опцию `reject_if: :all_blank`, чтобы не было ошибок, если добавляем с пустыми файлами ответ

2017-07-14 19:56 UTC, iBublik commented on app/models/question.rb
> +  accepts_nested_attributes_for :attachments
Тут тоже `reject_if: :all_blank`

2017-07-14 19:56 UTC, iBublik commented on db/migrate/20170708141302_convert_attachment_to_polymorphic.rb
> +    remove_index :attachments, :question_id
Если меняешь поля, добавленные в рамках этой фичи, то лучше просто откатить миграцию и поправить ее. Так меньше мусора будет в папке с миграциями.

2017-07-14 19:56 UTC, iBublik commented on spec/acceptance/delete_file_from_answers_spec.rb
> +    answer.attachments.create(file: file)
Воспользуйся фабрикой. Чтоб на момент начала теста аттачмент был уже создан, используй бэнг-версию метода `given!`

2017-07-14 19:56 UTC, iBublik commented on spec/acceptance/delete_file_from_answers_spec.rb
> +  scenario 'Author deletes file', js: true do
Нужен тест для не-автора

2017-07-14 19:56 UTC, iBublik commented on spec/acceptance/delete_file_from_question_spec.rb
> +feature 'Delete files from question', %q{
Здесь замечания аналогичны тестам ответа

2017-07-14 19:56 UTC, iBublik commented on spec/controllers/attachments_controller_spec.rb
> +      user_question.attachments.create(file: file)
Это лучше было не в before блоке описывать, а в let блоке или даже в самом тесте. Потому что в каждом тесте нам нужен 1 файл, а создается 4 - чем больше тестов, тем больше времени они будут занимать, а запись в базу (особенно с файлами, там же еще на диск сохранение идет) дорогая операция

2017-07-14 19:56 UTC, iBublik commented on spec/controllers/attachments_controller_spec.rb
> +      it 'deletes attachment from answer' do
В описании указано, что аттачмент удаляется, а по факту нет (и не должен) :) Не забывай что цель спеков не только проверка кода, но и написание спецификации к системе

2017-07-15 08:38 UTC, yalokin commented on app/models/answer.rb
> +      prev_best.update(best: false) unless prev_best.empty?
Убрал, т.к. начала возникать такая ошибка в тесте"NoMethodError:
       undefined method `update!' for #<ActiveRecord::AssociationRelation []>
       Did you mean?  update"
Думал позже разобраться в чем дело. Почему так может происходить?

2017-07-15 10:04 UTC, yalokin commented on spec/acceptance/delete_file_from_answers_spec.rb
> +    answer.attachments.create(file: file)
А как в фабрике файл прикрепить? Гуглю, пока ничего путного не нашел

2017-07-15 13:17 UTC, vkurennov commented on app/models/answer.rb
> +      prev_best.update(best: false) unless prev_best.empty?
Потому что нет лучшего ответа и  строка   `prev_best = question.answers.where(best: true)` возвращает пустое значение. Ну и замена на update ничего не дает, у ActiveRecord::AssociationRelation [] нети метода update. Но вообще-то у тебя проверка стоит в unless на это дело.

Попробуй в строке где, идет получение предыдущего лучшего ответа добавить `.first`, тогда будет возвращаться либо объект либо nil

2017-07-15 13:18 UTC, vkurennov commented on spec/acceptance/delete_file_from_answers_spec.rb
> +    answer.attachments.create(file: file)
Вот посмотри [первый ответ](https://stackoverflow.com/questions/3294824/how-do-i-use-factory-girl-to-generate-a-paperclip-attachment)

2017-07-15 13:19 UTC, vkurennov approved these changes

2017-07-17 10:53 UTC, merged

2017-07-17 10:55 UTC, yalokin commented on spec/acceptance/delete_file_from_answers_spec.rb
> +    answer.attachments.create(file: file)
Вроде все получилось верно