Other ajax
yalokin/qna pull request #7
Opened 2017-08-02 09:16 UTC by yalokin

2017-08-02 11:05 UTC, vkurennov requested changes

2017-08-02 11:05 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    vote('up')
Используй символы для строк-констант

2017-08-02 11:05 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    if direction == 'up'
Как-то сильно сложно. А не проще, сразу +/- 1 передавать в качестве параметра?

2017-08-02 11:05 UTC, vkurennov commented on app/models/concerns/votable.rb
> +          increment!(:rating, 1)
А если сделать increment! но на -1, не будет ли то же, что и decrement?

2017-08-02 13:13 UTC, yalokin commented on app/models/concerns/votable.rb
> +          increment!(:rating, 1)
Да, но как-то по смыслу некрасиво получится же

2017-08-03 06:07 UTC, iBublik requested changes

2017-08-03 06:07 UTC, iBublik commented on app/controllers/concerns/voted.rb
> +  def vote(direction)
Параметр уже не direction, а value

2017-08-03 06:07 UTC, iBublik commented on app/models/concerns/votable.rb
> +  def vote(user, direction)
Тут тоже не direction, а value

2017-08-03 06:07 UTC, iBublik commented on app/models/concerns/votable.rb
> +      increment!(:rating, direction)
Рекомендация - для счетчиков лучше использовать [increment_counter](http://api.rubyonrails.org/classes/ActiveRecord/CounterCache/ClassMethods.html#method-i-increment_counter). Там значение счетчика увеличивается через SQL запрос, это позволит избежать race condition - если два пользователя лайкнули сущность одновременно, то один голос может потеряться. Рельсовый increment загружает модель в память и высчитывает новое значение, если это происходит одновременно у двух пользователей, то рельса просто не знает о другом изменении.

2017-08-03 06:07 UTC, iBublik commented on app/models/concerns/votable.rb
> +    if voted?(user)
Я бы делал `return unless voted?(user)`, чтоб избавиться от вложенности

2017-08-03 06:07 UTC, iBublik commented on app/models/concerns/votable.rb
> +        if vote_for(user).value == 1
Можно от условия избавиться, просто делай `increment!(:rating, vote_for(user).value * -1)`

2017-08-03 06:07 UTC, iBublik commented on app/models/concerns/votable.rb
> +    votes.where(user: user).first if user
А проверка на наличие user нужна?
И можно сделать `votes.find_by(user: user)` для краткости

2017-08-03 06:07 UTC, iBublik commented on app/models/vote.rb
> +  validates :value, uniqueness: { scope: [:user_id, :votable_id, :votable_type] }
Не вижу особого смысла в этой валидации. Чтоб обеспечить контроль целостности данных, можно не уровне базы сделать уникальный индекс

2017-08-03 06:07 UTC, iBublik commented on db/migrate/20170720154020_create_votes.rb
> +      t.references :user, index: true
Не забывай про внешние ключи, индекс создается по умолчанию

2017-08-03 06:07 UTC, iBublik commented on spec/acceptance/vote_for_answer_spec.rb
> +      expect(page).to have_no_link 'Vote down'
Проверь тогда уж что и ссылки `Cancel vote` нет

2017-08-03 06:07 UTC, iBublik commented on spec/acceptance/vote_for_answer_spec.rb
> +      click_on 'Vote up'
Наверно лучше выводить только ссылку "Cancel vote", если пользователь уже проголосовал. Ну это уже хотелки :)

2017-08-03 06:07 UTC, iBublik commented on spec/acceptance/vote_for_answer_spec.rb
> +      click_on 'Vote up'
Лучше заранее подготовить данные для теста (создать ответ с голосом пользователя). Такой тест будет быстрее и проверять будет только отмену голоса (сейчас он может упасть если само голосование сломалось, это не относится конкретно к данному тесту).

2017-08-03 06:07 UTC, iBublik commented on spec/controllers/concerns/votable_spec.rb
> +      it 'set vote up to resource' do
Описание путает

2017-08-03 06:07 UTC, iBublik commented on spec/controllers/concerns/votable_spec.rb
> +        expect { patch :vote_up, params: { id: votable }, format: :json }.to_not change(Vote, :count)
Нам скорее важно проверить, что рейтинг не поменялся.

2017-08-03 06:07 UTC, iBublik commented on spec/controllers/concerns/votable_spec.rb
> +      let(:resource) { controller.controller_name.singularize.to_sym }
Это можно вынести выше, т.к. во всех тестах повторяется

2017-08-03 06:07 UTC, iBublik commented on spec/controllers/concerns/votable_spec.rb
> +      patch :vote_down, params: { id: votable }, format: :json
Подготовь данные для теста, чтоб не делать избыточных действий (этот экшн вообще не относится к тестируемому функционалу)

2017-08-03 06:07 UTC, iBublik commented on spec/controllers/concerns/votable_spec.rb
> +      expect { patch :cancel_vote, params: { id: votable}, format: :json }.to_not change(Vote, :count)
Какая-то странная проверка. Главное - проверить, что рейтинг изменился (если было +1, то вычлась единица из рейтинга).

2017-08-03 06:07 UTC, iBublik commented on spec/models/concerns/votable_spec.rb
> +RSpec.shared_examples 'votable' do
Лучше shared_examples называть по аналогии с консернами. А то сейчас 2 шаред экзампла с одинаковыми именами

2017-08-03 06:07 UTC, iBublik commented on spec/models/concerns/votable_spec.rb
> +  describe '#vote_up' do
В моделях нет таких методов

2017-08-03 06:07 UTC, iBublik commented on spec/models/concerns/votable_spec.rb
> +      expect(Vote.last.value).to eq 1
Лучше тут использовать `votable.vote_for(user)` - так мы точно проверяем голос пользователя за данный ресурс, а не просто последний созданный голос

2017-08-03 06:07 UTC, iBublik commented on spec/models/concerns/votable_spec.rb
> +      expect(Vote.last.value).to eq 1
Кстати метод я бы назвал `vote_by`, так лучше суть отражается

2017-08-03 06:07 UTC, iBublik commented on spec/models/concerns/votable_spec.rb
> +end
Где же тесты на cancel_vote и vote_for?

2017-08-03 07:17 UTC, yalokin commented on app/models/concerns/votable.rb
> +      increment!(:rating, direction)
Важное замечание, видел использование этого метода, но конструкция self.class.decrement_counter(:rating, self) вызывала недоумение

2017-08-03 07:34 UTC, yalokin commented on app/models/concerns/votable.rb
> +        if vote_for(user).value == 1
здесь тоже стал использовать increment_counter, поэтому пока оставлю условие. Или же здесь ситуация с коллизией невозможна и лучше сделать по-твоему?

2017-08-03 09:07 UTC, yalokin commented on db/migrate/20170720154020_create_votes.rb
> +      t.references :user, index: true
а можно пояснить, убрать index: true?

2017-08-03 09:13 UTC, yalokin commented on spec/acceptance/vote_for_answer_spec.rb
> +      click_on 'Vote up'
Подумаю как это сделать )

2017-08-03 09:17 UTC, yalokin commented on spec/acceptance/vote_for_answer_spec.rb
> +      click_on 'Vote up'
Исходил из мысли, надо эмулировать действия во фронтэнде

2017-08-04 11:00 UTC, iBublik commented on spec/acceptance/vote_for_answer_spec.rb
> +      click_on 'Vote up'
Надо эмулировать _тестируемые_ действия. Голосование у тебя отдельно проверяется, тут надо проверить только отмену голоса. Ты ведь не регистрируешься с нуля в каждом тесте :)

2017-08-04 11:12 UTC, vkurennov requested changes

2017-08-04 11:12 UTC, vkurennov commented on app/assets/javascripts/vote.js.coffee
> +    obj = $.parseJSON(e.detail[2].response)
Ктсати, в detail под индексом 1 или 0 (точно не помню) приходит уже распарсенный json, можно его не парсить

2017-08-04 11:12 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    vote(+1)
Ну плюс указывать явно не нужно, он же по-умолчанию

2017-08-04 11:12 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    render json: { id: @votable.id, content: content, controller: controller_name.singularize }, status: status
Лучше бы не контроллер передавать, а votable_type, это как-то логичнее, чем на имя контроллера завязываться

2017-08-04 11:12 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def vote(user, value)
Видел уже этот код, можно сделать его более универсальными и избавиться от if/elsif. У тебя фактически, все отличие в одной строке, а ты зачем-то весь код добавляешь в транзакции. Упрости

2017-08-04 11:12 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      reload
Зачем reload делать внутри транзакции?

2017-08-04 15:39 UTC, yalokin commented on app/assets/javascripts/vote.js.coffee
> +    obj = $.parseJSON(e.detail[2].response)
Обратил внимание, что в ответе дублирование было, но что это был json не распознал

2017-08-04 17:35 UTC, yalokin commented on app/controllers/concerns/voted.rb
> +    render json: { id: @votable.id, content: content, controller: controller_name.singularize }, status: status
А как же его достать, если известны только текущий пользовать и id ресурса? Через пользователя можно, но идентификаторы вопроса и ответа могут пересекаться

2017-08-05 08:01 UTC, iBublik commented on app/controllers/concerns/voted.rb
> +    render json: { id: @votable.id, content: content, controller: controller_name.singularize }, status: status
Ты ведь уже загрузил инстанс модели, возьми тип оттуда - `@votable.class.name.downcase`. Но имхо, тут больше претензия к имени ключа в json.

2017-08-05 08:01 UTC, iBublik commented on app/controllers/concerns/voted.rb
> +    vote(1)
Кстати, без скобочек с плюсом/минусом код выглядит краисво :) Это не замечание, просто есть в Ruby такой стиль написания когда, называется poetry mode - в данном случае выглядит вполне уместно
`vote +1 / vote -1`

2017-08-05 08:01 UTC, iBublik commented on spec/models/concerns/votable_spec.rb
> +  describe '#vote(user, 1)' do
Разделение на 2 дескрайба в зависимости от значения параметров избыточно - метод-то один и тот же описан. И вообще я не стал бы описывать оба кейза, они отличаются только значением, на которое изменяется рейтинг. А это ты уже протестил в экшенах контроллера (vote_up/vote_down).

2017-08-05 08:14 UTC, vkurennov approved these changes

2017-08-07 13:55 UTC, yalokin commented on spec/acceptance/vote_for_answer_spec.rb
> +      click_on 'Vote up'
Мысль понял )

2017-08-07 14:14 UTC, yalokin commented on app/models/concerns/votable.rb
> +      reload
А как правильно делать? Ошибка в том, что надо после destroy или же вообще за транзакцией?  Я исходил из того, что нет смысла перезагружать объект, если данные не записались

2017-08-07 14:28 UTC, merged